# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 02:32
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, validators=[account.models.phone_validate], verbose_name='\u7528\u6237\u540d')),
                ('nick_name', models.CharField(max_length=100, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('birthday', models.DateField(verbose_name='\u751f\u65e5')),
                ('city', models.CharField(max_length=100, verbose_name='\u6240\u5728\u57ce\u5e02')),
                ('head_img', models.CharField(max_length=100, verbose_name='\u5934\u50cf\u5730\u5740')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
