# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='account',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
