# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='todo\u6807\u9898')),
                ('todo_time', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5907\u6ce8')),
                ('sms_remid', models.BooleanField(default=False, verbose_name='\u77ed\u4fe1\u63d0\u9192')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
                'db_table': 'todo',
            },
        ),
    ]
