# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityid', models.IntegerField(default=0, verbose_name='\u57ce\u5e02id')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='\u57ce\u5e02\u540d')),
                ('citycode', models.CharField(blank=True, default='', max_length=100, verbose_name='\u57ce\u5e02\u7f16\u7801')),
                ('parentid', models.IntegerField(default=0, verbose_name='\u7236\u57ce\u5e02id')),
            ],
            options={
                'db_table': 'city_info',
            },
        ),
        migrations.CreateModel(
            name='StarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astroid', models.IntegerField(default=0, verbose_name='\u661f\u5ea7id')),
                ('astroname', models.CharField(blank=True, default='', max_length=100, verbose_name='\u661f\u5ea7\u540d\u79f0')),
                ('date', models.CharField(blank=True, default='', max_length=100, verbose_name='\u661f\u5ea7\u65e5\u671f')),
                ('pic', models.CharField(blank=True, default='', max_length=100, verbose_name='\u661f\u5ea7\u56fe\u7247url')),
            ],
            options={
                'db_table': 'star_info',
            },
        ),
    ]
