# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='banner\u6807\u9898')),
                ('picture_url', models.CharField(blank=True, default='', max_length=100, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('is_use', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'ordering': ('created',),
                'db_table': 'banner',
            },
        ),
    ]
